#!/usr/bin/env bash
#Script that displays numbers from 1 to 100

x=1
until ((x==101))
do
	if ((x%15==0)); then
		echo "FizzBuzz"
	elif ((x%3==0)); then
		echo "Fizz"
	elif ((x==5)); then
		echo "Buzz"
	else
		echo "$x"
	fi
	((x++))
done
