#!/usr/bin/env bash
#Script that displays hours from 0 to 12 and minutes from 1 to 59

Hours=0
while (( Hours<=12 ))
do
    echo Hour: "$Hours"
    min=1
    while (( min<=59 ))
    do
	echo "$min"
	(( min++ ))
    done
    (( Hours++ ))
done
