#!/usr/bin/env bash
# Displays its own PID

echo "$$" > /var/run/myscript.pid

#Displays To infinity and beyond indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 3
    trap "echo 'I hate the kill command' ; rm -rf /var/run/myscript.pid ; exit" SIGTERM
    trap "echo 'Y U no love me?!' ; exit" SIGINT
    trap "rm -rf /var/run/myscript.pid ; exit" SIGQUIT
done
