#!/usr/bin/env bash
# Displays its own PID

echo "$$" > /var/run/myscript.pid

trap "echo 'I hate the kill command' ; rm -rf /var/run/myscript.pid ; exit" SIGTERM
trap "echo 'Y U no love me?!' ; exit" SIGINT

while true
do
    echo "To infinity and beyond"
    sleep 3
   done

trap "rm -rf /var/run/myscript.pid | sudo pkill -9 -f /var/run/myscript.pid" SIGQUIT
