#!/usr/bin/env bash
# ....
echo "$$" > /var/run/myscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
#Displays To infinity and beyond indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 3
done
trap "pkill -15 -f /var/run/myscript.pid" SIGQUIT SIGTERM
