#!/usr/bin/env bash
# Displays its own PID

if [ "$1" == "start" ]
then
    echo "manage_my_process started"
        ./manage_my_process &
    echo "$!" > /var/run/my_process.pid

elif [ "$1" == "stop" ]
then
    echo "manage_my_process stopped"
    pkill /var/run/my_process.pid
    sudo pkill -f "./manage_my_process"
    rm /var/run/my_process.pid 

elif [ "$1" == "restart" ]
then
echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
