#!/usr/bin/env bash
# Displays its own PID

if [ "$1" == "start" ]
then
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    echo "manage_my_process started" 

elif [ "$1" == "stop" ]
then
echo "manage_my_process stopped" 
    pkill -f ./manage_my_process
    rm -rf /var/run/my_process.pid
    

elif [ "$1" == "restart" ]
then
echo "manage_my_process restarted"
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
