#!/usr/bin/env bash
# Displays its own PID

tmpfile="/var/run/my_process.pid"

if [ "$1" == "start" ]
then
   echo "manage_my_process started"
    ./manage_my_process &
    echo "$!" > "$tmpfile"

elif [ "$1" == "stop" ]
then
echo "manage_my_process stopped" 
    
    sudo pkill -f "./manage_my_process"
    rm "$tmpfile"   

elif [ "$1" == "restart" ]
then
echo "manage_my_process restarted"
   
    sudo pkill -f "./manage_my_process"
    rm "$tmpfile" 
    ./manage_my_process &
    echo "$!" > "$tmpfile"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
