#!/usr/bin/env bash
# Script receives kill signal from another script running in another terminal

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done